### PR TITLE
Add copee

### PR DESCRIPTION
**Pull request by styfle**
Copy text from browser to clipboard...natively!

https://github.com/styfle/copee

This package is less than 1 kB 😄

### CODE REVIEW

**Comment by parro-it** [comment]
Thank you!
But you should improve the docs. In details I didn't understand what this snippet from readme means:

```
import { toClipboard } from 'copee';
console.log('ESM: We found a ', typeof toClipboard);
```

And you never mentioned the `fromElement` function that you exported.

**Comment by styfle** [comment]
The snippet just proves that you can import from Node.js

This is a browser only package so you can't actually execute the function from Node

The usage is better demonstrated on the docs website here: https://copee.ceriously.com

**Comment by styfle** [comment]
@parro-it I would be happy to accept a PR if you think there is a better way to demonstrate the usage 😄

**Comment by parro-it** [comment]
> @parro-it I would be happy to accept a PR if you think there is a better way to demonstrate the usage 😄

Sorry, I haven't the time ATM.

> The snippet just proves that you can import from Node.js

I think you can use the provided functions to make the same point, it would be useful for the users

**Comment by styfle** [comment]
> I think you can use the provided functions to make the same point, it would be useful for the users

I think it would be misleading to show Node usage that doesn't actually work (throws at runtime). If you execute `copee.fromElement()` Node, it will fail at runtime because there is no DOM elements in Node.

The point of the Node Usage section is to demonstrate the imports so you can use bundlers (that run in Node) such as webpack or browserify.

**Comment by styfle** [comment]
I went ahead and removed Node.js usage from the README to avoid confusion.

I hope this is satisfactory 👍

**Comment by parro-it** [comment]
Ok, thank you!

**Pull request merged**
