### PR TITLE
Add article »The cost of small modules«

### PR DESCRIPTION
**Pull request by mischah**
See https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/

### CODE REVIEW

**Comment by jonschlinkert** [comment]
The benefits of small modules is such a well established fact, isn't this like asking to add a "flat world" argument to a cartography website?

**Comment by mischah** [comment]
Mhmm. I don’t think so. Its about performance. And which module bundler works the best in terms of performance.

**Comment by jonschlinkert** [comment]
> Its about performance. And which module bundler works the best in terms of performance.

Node.js performance, or browser performance? 

edit: sorry, I didn't mean to give you a hard time. There are other similar articles mentioned on the readme, I can see how it makes sense in that context. However, I'm sensitive to this kind of information because it's very easy for newcomers to take as fact when the reader isn't knowledgeable enough to question things like "does `node_modules` really consist mostly of libs like `_.uniq` and `once`?", which obviously is very naive. Or "is the author giving me an alternative to these specialized modules, or just being alarmist?".  Just my 2c.

**Comment by parro-it** [comment]
I like that article and find it really useful, thanks for the suggestion @mischah 

@jonschlinkert I understand you're concerns, but the cost of using many small modules in the browser is real, the article help to know how best to afford it.

**Comment by mischah** [comment]
@jonschlinkert @parro-it 👌

**Pull request merged**
