### PR TITLE
Add array-swap

### PR DESCRIPTION
**Pull request by michaelzoidl**
Hi, 
for my last redux project i had to develop two micro-modules to edit a state (array) without changing the passed arrays.
I thought those two would be fit good in this repo :)

michael

### CODE REVIEW

**Comment by parro-it** [comment]
Hi, thank you for the contribution. Please split them in two different PR, I want to keep track of when/who add each library.

I have some difficult understanding what array-portal do. What is a Portal? Maybe you want to add some explanation or reference link in its readme...

**Comment by parro-it** [comment]
Oh and wait for the first PR to be merged before publishing the other, or they conflict each other

**Comment by michaelzoidl** [comment]
Ok i removed the `array-portal` link :) 

If the `array-swap` package is ok we could merge it and i update later the `array-portal` readme and make a new PR.

**Comment by parro-it** [comment]
Thank you!

**Comment by michaelzoidl** [comment]
Awesome :) Thanks

**Pull request merged**
