### PR TITLE
doc: add npm-deprecated-check to the cli section

### PR DESCRIPTION
**Pull request by KID-joker**
[npm-deprecated-check](https://github.com/KID-joker/npm-deprecated-check): Check the packages of current project, global or specified is deprecated, and recommend alternative packages through OpenAI.

### CODE REVIEW

**Comment by parro-it** [comment]
Would you mind adding your package in a new `Tools` section? This is list is really about libraries, not cli apps, but I guess your one can be of great help to whom is using a lot of small libs...
Thank you!

**Comment by KID-joker** [comment]
OK! Put it behind the other section?

**Comment by parro-it** [comment]
Yes , that's fine!

**Comment by KID-joker** [comment]
It's done.

**Comment by parro-it** [comment]
Thank you so much

**Comment by KID-joker** [comment]
It's my pleasure

**Pull request merged**
