### PR TITLE
adds pad-left

### PR DESCRIPTION
**Pull request by jonschlinkert**
@parro-it I was going to add other modules but noticed in the contributor guidelines that a single module should be added per pr. would you consider a pr with additional modules? 

p.s. if not no worries, I can do separate prs

### CODE REVIEW

**Comment by parro-it** [comment]
Hey @jonschlinkert, really hot module! I noticed it get confused with [azer one](https://github.com/azer/left-pad/issues/4) yesterday :smile:

I will prefer individual PR, or if you want I can give you repo access so you can push directly to it...

**Comment by jonschlinkert** [comment]
> I will prefer individual PR, or if you want I can give you repo access so you can push directly to it...

sure that would be great! I will still ask for your review before merging though. thanks!

**Comment by parro-it** [comment]
:+1: done!

**Comment by jonschlinkert** [comment]
awesome thanks!

**Pull request merged**
