### PR TITLE
added read-file-utf8

### PR DESCRIPTION
**Pull request by fibo**
Please see [Usage section](https://github.com/fibo/read-file-utf8#usage).

### CODE REVIEW

**Comment by parro-it** [comment]
Thank you for the contribution, but this module seems implementing an unnecessary abstraction, according  to me.
I usually known in advance if I need the sync or async version of readFile, so just use that. 
The saved typing on the encoding param is not sufficient to justify a module dependency.

Grazie! Sorry!

**Comment by fibo** [comment]
Oki, your point of view makes sense.

So I guess you have the same opinion, for write-file-utf8.

I still think it is a useful package, since I don't have to write always `'utf8'` and the type of input is reduced to a `{String}` instead of `{String|Buffer}`.

**Comment by parro-it** [comment]
Sorry again, but no.  If you look at the node docs, you'll see for writeFile:

> The encoding option is ignored if data is a buffer. It defaults to 'utf8'.

So you are just providing an option value that is already the default, 
and disallowing a data type that won't work only because you provide the encoding option.

Moreover, your function does not provide a way for the caller to know when the write operation complete. You should accept a callback as arg or return a `Promise`.

**Comment by fibo** [comment]
The _read-file-utf8_ package  accepts an optional callback, see [its API section](https://github.com/fibo/read-file-utf8#readfilefilepath-callback). If provided, it behaves async, otherwise it uses the sync mode.

While _write-file-utf8_, by now provides a default callback that just throws the error. It is a good point to add an optional callback or return a Promise.

**Pull request closed without merging**
